### ISSUE TITLE
Edit Button throws System Error 

### ISSUE THREAD

**Issue by nash90** [nash90/NewMalika#14]
It was working well till last deploy, dont know what happened

**Comment by shirishdwa** [comment]
![a](https://cloud.githubusercontent.com/assets/6326097/11989528/b620da16-aa42-11e5-8fcf-98a73172e5b2.png)

This must be the culprit if it was working before deploy.
By "it was working" do u mean the client info could be edited. I quickly looked through MalikaEditController but dint find any line that returns an edit form to edit the client chosen.

**Comment by nash90** [comment]
Yup, it was the removal of type="button" attribute from the button tag. I corrected and its working. made a new pull request request please check.

**Comment by shirishdwa** [comment]
Cool. Merged it. Thanks I will close this issue
